//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.defaultmain {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="defaultmain.defaultmainSoap")]
    public interface defaultmainSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsoleApp1.defaultmain.HelloWorldResponse HelloWorld(ConsoleApp1.defaultmain.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.defaultmain.HelloWorldResponse> HelloWorldAsync(ConsoleApp1.defaultmain.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name CheckEvenOddResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEvenOdd", ReplyAction="*")]
        ConsoleApp1.defaultmain.CheckEvenOddResponse CheckEvenOdd(ConsoleApp1.defaultmain.CheckEvenOddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEvenOdd", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.defaultmain.CheckEvenOddResponse> CheckEvenOddAsync(ConsoleApp1.defaultmain.CheckEvenOddRequest request);
        
        // CODEGEN: Generating message contract since element name ConvertToDollarResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToDollar", ReplyAction="*")]
        ConsoleApp1.defaultmain.ConvertToDollarResponse ConvertToDollar(ConsoleApp1.defaultmain.ConvertToDollarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToDollar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.defaultmain.ConvertToDollarResponse> ConvertToDollarAsync(ConsoleApp1.defaultmain.ConvertToDollarRequest request);
        
        // CODEGEN: Generating message contract since element name outType from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrencyConvertion", ReplyAction="*")]
        ConsoleApp1.defaultmain.GetCurrencyConvertionResponse GetCurrencyConvertion(ConsoleApp1.defaultmain.GetCurrencyConvertionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrencyConvertion", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.defaultmain.GetCurrencyConvertionResponse> GetCurrencyConvertionAsync(ConsoleApp1.defaultmain.GetCurrencyConvertionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.defaultmain.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsoleApp1.defaultmain.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.defaultmain.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsoleApp1.defaultmain.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckEvenOddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckEvenOdd", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.defaultmain.CheckEvenOddRequestBody Body;
        
        public CheckEvenOddRequest() {
        }
        
        public CheckEvenOddRequest(ConsoleApp1.defaultmain.CheckEvenOddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckEvenOddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num;
        
        public CheckEvenOddRequestBody() {
        }
        
        public CheckEvenOddRequestBody(int num) {
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckEvenOddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckEvenOddResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.defaultmain.CheckEvenOddResponseBody Body;
        
        public CheckEvenOddResponse() {
        }
        
        public CheckEvenOddResponse(ConsoleApp1.defaultmain.CheckEvenOddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckEvenOddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckEvenOddResult;
        
        public CheckEvenOddResponseBody() {
        }
        
        public CheckEvenOddResponseBody(string CheckEvenOddResult) {
            this.CheckEvenOddResult = CheckEvenOddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToDollarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToDollar", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.defaultmain.ConvertToDollarRequestBody Body;
        
        public ConvertToDollarRequest() {
        }
        
        public ConvertToDollarRequest(ConsoleApp1.defaultmain.ConvertToDollarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToDollarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num;
        
        public ConvertToDollarRequestBody() {
        }
        
        public ConvertToDollarRequestBody(int num) {
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToDollarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToDollarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.defaultmain.ConvertToDollarResponseBody Body;
        
        public ConvertToDollarResponse() {
        }
        
        public ConvertToDollarResponse(ConsoleApp1.defaultmain.ConvertToDollarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToDollarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertToDollarResult;
        
        public ConvertToDollarResponseBody() {
        }
        
        public ConvertToDollarResponseBody(string ConvertToDollarResult) {
            this.ConvertToDollarResult = ConvertToDollarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyConvertionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyConvertion", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.defaultmain.GetCurrencyConvertionRequestBody Body;
        
        public GetCurrencyConvertionRequest() {
        }
        
        public GetCurrencyConvertionRequest(ConsoleApp1.defaultmain.GetCurrencyConvertionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrencyConvertionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int inAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string outType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int outRate;
        
        public GetCurrencyConvertionRequestBody() {
        }
        
        public GetCurrencyConvertionRequestBody(int inAmount, string outType, int outRate) {
            this.inAmount = inAmount;
            this.outType = outType;
            this.outRate = outRate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyConvertionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyConvertionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.defaultmain.GetCurrencyConvertionResponseBody Body;
        
        public GetCurrencyConvertionResponse() {
        }
        
        public GetCurrencyConvertionResponse(ConsoleApp1.defaultmain.GetCurrencyConvertionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrencyConvertionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrencyConvertionResult;
        
        public GetCurrencyConvertionResponseBody() {
        }
        
        public GetCurrencyConvertionResponseBody(string GetCurrencyConvertionResult) {
            this.GetCurrencyConvertionResult = GetCurrencyConvertionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface defaultmainSoapChannel : ConsoleApp1.defaultmain.defaultmainSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class defaultmainSoapClient : System.ServiceModel.ClientBase<ConsoleApp1.defaultmain.defaultmainSoap>, ConsoleApp1.defaultmain.defaultmainSoap {
        
        public defaultmainSoapClient() {
        }
        
        public defaultmainSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public defaultmainSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public defaultmainSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public defaultmainSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.defaultmain.HelloWorldResponse ConsoleApp1.defaultmain.defaultmainSoap.HelloWorld(ConsoleApp1.defaultmain.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsoleApp1.defaultmain.HelloWorldRequest inValue = new ConsoleApp1.defaultmain.HelloWorldRequest();
            inValue.Body = new ConsoleApp1.defaultmain.HelloWorldRequestBody();
            ConsoleApp1.defaultmain.HelloWorldResponse retVal = ((ConsoleApp1.defaultmain.defaultmainSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.defaultmain.HelloWorldResponse> ConsoleApp1.defaultmain.defaultmainSoap.HelloWorldAsync(ConsoleApp1.defaultmain.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.defaultmain.HelloWorldResponse> HelloWorldAsync() {
            ConsoleApp1.defaultmain.HelloWorldRequest inValue = new ConsoleApp1.defaultmain.HelloWorldRequest();
            inValue.Body = new ConsoleApp1.defaultmain.HelloWorldRequestBody();
            return ((ConsoleApp1.defaultmain.defaultmainSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.defaultmain.CheckEvenOddResponse ConsoleApp1.defaultmain.defaultmainSoap.CheckEvenOdd(ConsoleApp1.defaultmain.CheckEvenOddRequest request) {
            return base.Channel.CheckEvenOdd(request);
        }
        
        public string CheckEvenOdd(int num) {
            ConsoleApp1.defaultmain.CheckEvenOddRequest inValue = new ConsoleApp1.defaultmain.CheckEvenOddRequest();
            inValue.Body = new ConsoleApp1.defaultmain.CheckEvenOddRequestBody();
            inValue.Body.num = num;
            ConsoleApp1.defaultmain.CheckEvenOddResponse retVal = ((ConsoleApp1.defaultmain.defaultmainSoap)(this)).CheckEvenOdd(inValue);
            return retVal.Body.CheckEvenOddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.defaultmain.CheckEvenOddResponse> ConsoleApp1.defaultmain.defaultmainSoap.CheckEvenOddAsync(ConsoleApp1.defaultmain.CheckEvenOddRequest request) {
            return base.Channel.CheckEvenOddAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.defaultmain.CheckEvenOddResponse> CheckEvenOddAsync(int num) {
            ConsoleApp1.defaultmain.CheckEvenOddRequest inValue = new ConsoleApp1.defaultmain.CheckEvenOddRequest();
            inValue.Body = new ConsoleApp1.defaultmain.CheckEvenOddRequestBody();
            inValue.Body.num = num;
            return ((ConsoleApp1.defaultmain.defaultmainSoap)(this)).CheckEvenOddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.defaultmain.ConvertToDollarResponse ConsoleApp1.defaultmain.defaultmainSoap.ConvertToDollar(ConsoleApp1.defaultmain.ConvertToDollarRequest request) {
            return base.Channel.ConvertToDollar(request);
        }
        
        public string ConvertToDollar(int num) {
            ConsoleApp1.defaultmain.ConvertToDollarRequest inValue = new ConsoleApp1.defaultmain.ConvertToDollarRequest();
            inValue.Body = new ConsoleApp1.defaultmain.ConvertToDollarRequestBody();
            inValue.Body.num = num;
            ConsoleApp1.defaultmain.ConvertToDollarResponse retVal = ((ConsoleApp1.defaultmain.defaultmainSoap)(this)).ConvertToDollar(inValue);
            return retVal.Body.ConvertToDollarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.defaultmain.ConvertToDollarResponse> ConsoleApp1.defaultmain.defaultmainSoap.ConvertToDollarAsync(ConsoleApp1.defaultmain.ConvertToDollarRequest request) {
            return base.Channel.ConvertToDollarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.defaultmain.ConvertToDollarResponse> ConvertToDollarAsync(int num) {
            ConsoleApp1.defaultmain.ConvertToDollarRequest inValue = new ConsoleApp1.defaultmain.ConvertToDollarRequest();
            inValue.Body = new ConsoleApp1.defaultmain.ConvertToDollarRequestBody();
            inValue.Body.num = num;
            return ((ConsoleApp1.defaultmain.defaultmainSoap)(this)).ConvertToDollarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.defaultmain.GetCurrencyConvertionResponse ConsoleApp1.defaultmain.defaultmainSoap.GetCurrencyConvertion(ConsoleApp1.defaultmain.GetCurrencyConvertionRequest request) {
            return base.Channel.GetCurrencyConvertion(request);
        }
        
        public string GetCurrencyConvertion(int inAmount, string outType, int outRate) {
            ConsoleApp1.defaultmain.GetCurrencyConvertionRequest inValue = new ConsoleApp1.defaultmain.GetCurrencyConvertionRequest();
            inValue.Body = new ConsoleApp1.defaultmain.GetCurrencyConvertionRequestBody();
            inValue.Body.inAmount = inAmount;
            inValue.Body.outType = outType;
            inValue.Body.outRate = outRate;
            ConsoleApp1.defaultmain.GetCurrencyConvertionResponse retVal = ((ConsoleApp1.defaultmain.defaultmainSoap)(this)).GetCurrencyConvertion(inValue);
            return retVal.Body.GetCurrencyConvertionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.defaultmain.GetCurrencyConvertionResponse> ConsoleApp1.defaultmain.defaultmainSoap.GetCurrencyConvertionAsync(ConsoleApp1.defaultmain.GetCurrencyConvertionRequest request) {
            return base.Channel.GetCurrencyConvertionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.defaultmain.GetCurrencyConvertionResponse> GetCurrencyConvertionAsync(int inAmount, string outType, int outRate) {
            ConsoleApp1.defaultmain.GetCurrencyConvertionRequest inValue = new ConsoleApp1.defaultmain.GetCurrencyConvertionRequest();
            inValue.Body = new ConsoleApp1.defaultmain.GetCurrencyConvertionRequestBody();
            inValue.Body.inAmount = inAmount;
            inValue.Body.outType = outType;
            inValue.Body.outRate = outRate;
            return ((ConsoleApp1.defaultmain.defaultmainSoap)(this)).GetCurrencyConvertionAsync(inValue);
        }
    }
}
