//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webservicesp1n2.EvenOddWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EvenOddWebService.defaultmainSoap")]
    public interface defaultmainSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        webservicesp1n2.EvenOddWebService.HelloWorldResponse HelloWorld(webservicesp1n2.EvenOddWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<webservicesp1n2.EvenOddWebService.HelloWorldResponse> HelloWorldAsync(webservicesp1n2.EvenOddWebService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name CheckEvenOddResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEvenOdd", ReplyAction="*")]
        webservicesp1n2.EvenOddWebService.CheckEvenOddResponse CheckEvenOdd(webservicesp1n2.EvenOddWebService.CheckEvenOddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEvenOdd", ReplyAction="*")]
        System.Threading.Tasks.Task<webservicesp1n2.EvenOddWebService.CheckEvenOddResponse> CheckEvenOddAsync(webservicesp1n2.EvenOddWebService.CheckEvenOddRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public webservicesp1n2.EvenOddWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(webservicesp1n2.EvenOddWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public webservicesp1n2.EvenOddWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(webservicesp1n2.EvenOddWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckEvenOddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckEvenOdd", Namespace="http://tempuri.org/", Order=0)]
        public webservicesp1n2.EvenOddWebService.CheckEvenOddRequestBody Body;
        
        public CheckEvenOddRequest() {
        }
        
        public CheckEvenOddRequest(webservicesp1n2.EvenOddWebService.CheckEvenOddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckEvenOddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num;
        
        public CheckEvenOddRequestBody() {
        }
        
        public CheckEvenOddRequestBody(int num) {
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckEvenOddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckEvenOddResponse", Namespace="http://tempuri.org/", Order=0)]
        public webservicesp1n2.EvenOddWebService.CheckEvenOddResponseBody Body;
        
        public CheckEvenOddResponse() {
        }
        
        public CheckEvenOddResponse(webservicesp1n2.EvenOddWebService.CheckEvenOddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckEvenOddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckEvenOddResult;
        
        public CheckEvenOddResponseBody() {
        }
        
        public CheckEvenOddResponseBody(string CheckEvenOddResult) {
            this.CheckEvenOddResult = CheckEvenOddResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface defaultmainSoapChannel : webservicesp1n2.EvenOddWebService.defaultmainSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class defaultmainSoapClient : System.ServiceModel.ClientBase<webservicesp1n2.EvenOddWebService.defaultmainSoap>, webservicesp1n2.EvenOddWebService.defaultmainSoap {
        
        public defaultmainSoapClient() {
        }
        
        public defaultmainSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public defaultmainSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public defaultmainSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public defaultmainSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webservicesp1n2.EvenOddWebService.HelloWorldResponse webservicesp1n2.EvenOddWebService.defaultmainSoap.HelloWorld(webservicesp1n2.EvenOddWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            webservicesp1n2.EvenOddWebService.HelloWorldRequest inValue = new webservicesp1n2.EvenOddWebService.HelloWorldRequest();
            inValue.Body = new webservicesp1n2.EvenOddWebService.HelloWorldRequestBody();
            webservicesp1n2.EvenOddWebService.HelloWorldResponse retVal = ((webservicesp1n2.EvenOddWebService.defaultmainSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webservicesp1n2.EvenOddWebService.HelloWorldResponse> webservicesp1n2.EvenOddWebService.defaultmainSoap.HelloWorldAsync(webservicesp1n2.EvenOddWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<webservicesp1n2.EvenOddWebService.HelloWorldResponse> HelloWorldAsync() {
            webservicesp1n2.EvenOddWebService.HelloWorldRequest inValue = new webservicesp1n2.EvenOddWebService.HelloWorldRequest();
            inValue.Body = new webservicesp1n2.EvenOddWebService.HelloWorldRequestBody();
            return ((webservicesp1n2.EvenOddWebService.defaultmainSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webservicesp1n2.EvenOddWebService.CheckEvenOddResponse webservicesp1n2.EvenOddWebService.defaultmainSoap.CheckEvenOdd(webservicesp1n2.EvenOddWebService.CheckEvenOddRequest request) {
            return base.Channel.CheckEvenOdd(request);
        }
        
        public string CheckEvenOdd(int num) {
            webservicesp1n2.EvenOddWebService.CheckEvenOddRequest inValue = new webservicesp1n2.EvenOddWebService.CheckEvenOddRequest();
            inValue.Body = new webservicesp1n2.EvenOddWebService.CheckEvenOddRequestBody();
            inValue.Body.num = num;
            webservicesp1n2.EvenOddWebService.CheckEvenOddResponse retVal = ((webservicesp1n2.EvenOddWebService.defaultmainSoap)(this)).CheckEvenOdd(inValue);
            return retVal.Body.CheckEvenOddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webservicesp1n2.EvenOddWebService.CheckEvenOddResponse> webservicesp1n2.EvenOddWebService.defaultmainSoap.CheckEvenOddAsync(webservicesp1n2.EvenOddWebService.CheckEvenOddRequest request) {
            return base.Channel.CheckEvenOddAsync(request);
        }
        
        public System.Threading.Tasks.Task<webservicesp1n2.EvenOddWebService.CheckEvenOddResponse> CheckEvenOddAsync(int num) {
            webservicesp1n2.EvenOddWebService.CheckEvenOddRequest inValue = new webservicesp1n2.EvenOddWebService.CheckEvenOddRequest();
            inValue.Body = new webservicesp1n2.EvenOddWebService.CheckEvenOddRequestBody();
            inValue.Body.num = num;
            return ((webservicesp1n2.EvenOddWebService.defaultmainSoap)(this)).CheckEvenOddAsync(inValue);
        }
    }
}
